# 389. Find the Difference
# https://leetcode.com/problems/find-the-difference/
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

from collections import Counter
class Solution(object):
    def findTheDifference(self, s, t):
        return (Counter(t) - Counter(s)).popitem()[0]
